general:
  debug: false
  instance_name: 'The Keep Search'
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: 'duckduckgo'
  default_lang: 'en'

server:
  port: 8080
  bind_address: '0.0.0.0'
  secret_key: 'thekeep-searxng-secret-2026'
  limiter: false
  public_instance: false

ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: dark

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false
